# Generated by Django 3.1.1 on 2020-09-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=1048576)),
                ('title', models.CharField(max_length=64)),
                ('link', models.IntegerField()),
            ],
        ),
    ]
